services:
  ai-fall:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-fall
    volumes:
      - ./app/data:/app/data
    ports:
      - "8889:8889"
    environment:
      # Should use GPU
      - USE_GPU=false
      # Max number of video sources to handle
      - MAX_SOURCES=9
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia